# -*- coding: utf-8 -*-
"""semi final good code vateluthu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oO19TvgIBpwpiZk2WP-piPCk2mRvaeLX
"""

from google.colab import files
import zipfile
import os

# Upload the zip file
uploaded = files.upload()

# Extract it
zip_filename = next(iter(uploaded))
extract_path = "/content/vatteluttu_glyphs"
os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("✅ Folder extracted to:", extract_path)
print("📁 Files inside:", os.listdir(extract_path))

!pip install gradio opencv-python

import gradio as gr
import cv2
import os
import numpy as np

extract_path = "/content/vatteluttu_glyphs"

glyph_map = {
    "ka.png": "க",
    "na.png": "ந",
    "ma.png": "ம",
    "ti.png": "தி",
    "pa.png": "ப",
}

def match_image(image):
    try:
        input_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        input_img = cv2.resize(input_img, (100, 100))

        best_score = -1
        best_match = "பதிலில்லை"

        for filename in os.listdir(extract_path):
            if not filename.endswith(".png"):
                continue
            template = cv2.imread(os.path.join(extract_path, filename), 0)
            template = cv2.resize(template, (100, 100))

            result = cv2.matchTemplate(input_img, template, cv2.TM_CCOEFF_NORMED)
            _, score, _, _ = cv2.minMaxLoc(result)

            if score > best_score:
                best_score = score
                best_match = filename

        return glyph_map.get(best_match, "பதிலில்லை")
    except:
        return "படத்தை சரிபார்க்க முடியவில்லை"

# 🎨 Gradio UI
with gr.Blocks(title="வட்டெழுத்து உரை மாற்றி") as demo:
    gr.Markdown(
        """
        <div style="text-align:center; font-size: 26px; font-weight: bold;">🪶 வட்டெழுத்து → தமிழ் மாற்றி</div>
        <div style="text-align:center; font-size: 16px; margin-bottom: 20px;">பழைய தமிழ் எழுத்துக்களை படமாக பதிவேற்றுங்கள் – இங்கு அவை நவீன தமிழில் மொழிபெயர்க்கப்படும்.</div>
        """,
        elem_id="title",
    )

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(
                label="📷 உங்கள் வட்டெழுத்து படம்", type="numpy", image_mode="RGB", height=300
            )
            gr.Markdown("*உதாரணம்: கல்வெட்டு எழுத்துக்கள், தொல்லியல் நெறிமுறைகள் போன்றவை.*")
            submit_btn = gr.Button("🔍 மொழிபெயர்க்கவும்", size="lg")

        with gr.Column(scale=1):
            text_output = gr.Textbox(
                label="📜 மொழிபெயர்ப்பு (நவீன தமிழ்)",
                max_lines=1,
                show_copy_button=True,
                elem_id="output-text"
            )




    submit_btn.click(fn=match_image, inputs=image_input, outputs=text_output)

demo.launch()

!pip install gradio opencv-python